# Generated by Django 4.2 on 2023-04-18 12:29

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_servico_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'height': 480, 'width': 480}}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-mobile', 'mobile'), ('lni-statis-up', 'Grafico'), ('lni-users', 'Usuarios'), ('lni-rocket', 'foguete'), ('lni-layer', 'Desingn'), ('lni-cog', 'Engrenagem')], max_length=100, verbose_name='icone'),
        ),
    ]
