# Generated by Django 4.2 on 2023-04-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_funcionario_imagem_alter_servico_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-layer', 'Design'), ('lni-statis-up', 'Grafico'), ('lni-users', 'Usuarios'), ('lni-mobile', 'mobile'), ('lni-cog', 'Engrenagem'), ('lni-rocket', 'foguete')], max_length=100, verbose_name='icone'),
        ),
    ]
