# Generated by Django 4.2 on 2023-04-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_servico_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-users', 'Usuarios'), ('lni-statis-up', 'Grafico'), ('lni-mobile', 'mobile'), ('lni-rocket', 'foguete'), ('lni-cog', 'Engrenagem'), ('lni-layer', 'design')], max_length=100, verbose_name='icone'),
        ),
    ]
